
--Nguyễn Thị Ngọc Hân
--MSSV: 1712415
--------------------------------------------------
-----------------------------------------------LỖI DIRTY READ-----------------------------------------
----CODE LỖI
------T1
BEGIN TRAN
UPDATE THUCDON
SET SL_CONLAI= 4 WHERE MACN = 1 AND MAMON=1 AND NGAY='2019-30-11'
waitfor delay'00:00:05'



ROLLBACK
-----T2
BEGIN TRAN
SET TRAN ISOLATION LEVEL READ COMMITTED
SELECT SL_CONLAI FROM THUCDON WHERE MACN = 1 AND MAMON=1 AND NGAY='2019-30-11'


COMMIT

-------------------------------------------GIẢI PHÁP: SET CƠ CHẾ READ COMMITTED----------------------------
BEGIN TRAN
UPDATE THUCDON
SET SL_CONLAI= 4 WHERE MACN = 1 AND MAMON=1 AND NGAY='2019-30-11'
waitfor delay'00:00:05'



ROLLBACK
-----T2
BEGIN TRAN
SELECT SL_CONLAI 
FROM THUCDON 
WHERE MACN = 1 AND MAMON=1 AND NGAY='2019-30-11'

COMMIT

---------------------------------LỖI UNREPEATABLE READ------------------------------------------------------------
----LỖI
----T1
BEGIN TRAN
SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
waitfor delay'00:00:15'

SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
COMMIT
--T2
BEGIN TRAN
UPDATE THUCDON SET SL_CONLAI= 150
 WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
COMMIT
------------------------------------------GIẢI PHÁP--------------------------------------------
-------------------------------Set cơ chế khóa Repeatable Read
--T1
BEGIN TRAN
SET TRAN ISOLATION LEVEL REPEATABLE READ
SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
waitfor delay'00:00:15'

SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
COMMIT
--T2
BEGIN TRAN
UPDATE THUCDON SET SL_CONLAI= 150
 WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
COMMIT
-----------------------------------LỖI LOST UPDATE
--T1
BEGIN TRAN
SELECT SL FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1
waitfor delay'00:00:05'





UPDATE CHITIETDONHANG SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT

--T2
BEGIN TRAN
SELECT Sl FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1



UPDATE CHITIETDONHANG
SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT
----------------------------------------GIẢI PHÁP---------------------------------------------------------------
--------------------------------------set cơ chế khoá SERIALIZABLE-----------------------------------------------------------
--T1
--T1
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT SL FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1
waitfor delay'00:00:05'





UPDATE CHITIETDONHANG SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT
--T2
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT Sl FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1



UPDATE CHITIETDONHANG
SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT
----------------------------------------------------LỖI PHANTOMS-----------------------
--T1
BEGIN TRAN
SELECT * FROM THANHVIEN WHERE CHINHANHDK=1
waitfor delay'00:00:15'





SELECT * FROM THANHVIEN WHERE CHINHANHDK=1


COMMIT
--T2
BEGIN TRAN
INSERT INTO THANHVIEN VALUES (1000, N'Thành Viên 1000', N'123456', N'321907808', CAST(N'1970-11-09' AS Date), N'Phường 10, Quận 4 TP.HCM', 1, N'thanhvien999@gmail.com', 13000000, N'Gold')

COMMIT
----------------------------------------------------GIẢI PHÁP----------------------------------------
-------------------------------------------------SET CƠ CHẾ KHOÁ SERIALIZABLE
--T1
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT * FROM THANHVIEN WHERE CHINHANHDK=1
waitfor delay'00:00:15'





SELECT * FROM THANHVIEN WHERE CHINHANHDK=1


COMMIT
--T2
BEGIN TRAN
INSERT INTO THANHVIEN VALUES (1000, N'Thành Viên 1000', N'123456', N'321907808', CAST(N'1970-11-09' AS Date), N'Phường 10, Quận 4 TP.HCM', 1, N'thanhvien999@gmail.com', 13000000, N'Gold')

COMMIT
----------------------------------------------------LỖI DEADLOCK---------------------------------
--T1
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT SL FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1
waitfor delay'00:00:05'





UPDATE CHITIETDONHANG SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT
--T2
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT Sl FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1



UPDATE CHITIETDONHANG
SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1


COMMIT
----------------------------------GIẢI PHÁP-----HUỶ 1 GIAO TÁC GÂY RA DEADLOCK-------------------