CREATE DATABASE	HuongViet
GO
USE HuongViet
GO

CREATE TABLE CHINHANH
(
	MACN INT,
	TENCN NVARCHAR(100),
	SONHA NVARCHAR(100),
	PHUONG NVARCHAR(100),
	QUAN_HUYEN NVARCHAR(100),
	TINH_TP NVARCHAR(100),
	SDT VARCHAR(100)
	PRIMARY KEY(MACN)
)

CREATE TABLE THUCDON
(
	MACN INT,
	MAMON INT,
	NGAY DATE,
	SOLUONG INT,
	SL_CONLAI INT
	PRIMARY KEY(MACN,MAMON,NGAY)
)

CREATE TABLE MONAN
(
	MAMON INT,
	TENMON NVARCHAR(100),
	MALOAI INT,
	GIATIEN INT
	PRIMARY KEY(MAMON)
)

CREATE TABLE LOAIMON
(
	MALOAI INT,
	TENLOAI NVARCHAR(100)
	PRIMARY KEY(MALOAI)
)

CREATE TABLE CHITIETDONHANG
(
	MADH INT,
	MAMON INT,
	SL INT
	PRIMARY KEY(MADH,MAMON)
)

CREATE TABLE THANHVIEN
(
	MATV INT,
	TENTV NVARCHAR(100),
	MATKHAU VARCHAR(100),
	CMND VARCHAR(20),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	CHINHANHDK INT,
	EMAIL NVARCHAR(100),
	DIEMTICHLUY INT,
	LOAITHE NVARCHAR(100)
	PRIMARY KEY(MATV)
)

CREATE TABLE DONHANG
(
	MADH INT,
	MANV INT,
	MATV INT,
	MACN INT,
	NGAYDAT DATE,
	TRANGTHAI NVARCHAR(100),
	KENHDH NVARCHAR(50),
	THANHTIEN INT, --Tổng all món ăn
	TONGTIEN FLOAT, --Tổng all (... + phí ship + giảm giá + ... bla bla)
	PTTT NVARCHAR(100), --Phương thức thanh toán
	HUYDON BIT
	PRIMARY KEY(MADH)
)

CREATE TABLE NHANVIEN
(
	MANV INT,
	MACN INT,
	TENNV NVARCHAR(100),
	DIACHI NVARCHAR(100),
	CHUCVU NVARCHAR(100)
	PRIMARY KEY(MANV)
)

CREATE TABLE DHTRUCTUYEN
(
	MADH INT,
	NVGIAOHANG INT,
	TENKH NVARCHAR(100),
	SDT VARCHAR(100),
	SONHA NVARCHAR(100),
	PHUONG NVARCHAR(100),
	QUAN_HUYEN NVARCHAR(100),
	TINH_TP NVARCHAR(100),
	CHIPHI INT,
	TGGIAO TIME
	PRIMARY KEY(MADH)
)
GO

--FK
ALTER TABLE THUCDON ADD CONSTRAINT FK_TD_CN FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)
ALTER TABLE THUCDON ADD CONSTRAINT FK_TD_MA FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)

ALTER TABLE MONAN ADD CONSTRAINT FK_MA_LM FOREIGN KEY (MALOAI) REFERENCES LOAIMON(MALOAI)

ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK_CTDH_MA FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK_CTDH_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_CN FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)

ALTER TABLE THANHVIEN ADD CONSTRAINT FK_TV_CN FOREIGN KEY (CHINHANHDK) REFERENCES CHINHANH(MACN)

ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_TV FOREIGN KEY (MATV) REFERENCES THANHVIEN(MATV)
ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_CN FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)

ALTER TABLE DHTRUCTUYEN ADD CONSTRAINT FK_DHTT_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH)
ALTER TABLE DHTRUCTUYEN ADD CONSTRAINT FK_DHTT_NV FOREIGN KEY (NVGIAOHANG) REFERENCES NHANVIEN(MANV)
GO

--Khóa khác
ALTER TABLE THANHVIEN ADD CONSTRAINT U_CMND UNIQUE(CMND)
GO