USE HuongViet
GO


INSERT INTO CHINHANH VALUES(1,N'CN1',N'612 Ngô Gia Tự','0672346272','6','11',N'TP HCM')
GO
INSERT INTO THANHVIEN VALUES(1,N'Dương Khánh Vi','365213809','1999-04-24',N'Tiệm cầm đồ Anh Vũ, Huyện An Phú, Tỉnh An Giang',1,'quinnduong99@gmail.com',4900000,'Silver')
GO
INSERT INTO NHANVIEN VALUES(1,1,N'Trần Quốc Bảo',N'1230, Đào Duy Từ, Quận 10, TPHCM',N'Giao hàng'),
							(2,1,N'Nguyễn Thị Ngọc Hân',N'333, Cao Thắng, Quận 11, TPHCM',N'Lễ tân')
GO
INSERT INTO LOAIMON VALUES(1,N'Nước'),(2,N'Cơm')
GO
INSERT INTO MONAN VALUES(1,N'Cơm sườn 2 trứng',2,30000),(2,N'Cơm gà xối mỡ',2,25000),(3,N'Cam ép',1,20000),(4,N'Coca cola',1,10000)
GO
INSERT INTO THUCDON VALUES(1,1,'2016-10-05',700,57),(1,2,'2016-12-15',90,72),(1,3,'2016-08-19',1000,857),(1,4,'2016-07-05',9800,6753)
GO

/* ĐƠN HÀNG */
-- NV INSERT ĐƠN HÀNG
CREATE PROC sp_InDH 
	@MANV INT,
	@MATV INT,
	@MACN INT,
	@KENHDH NVARCHAR(100),
	@PTTT NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF((EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND MACN=@MACN))OR(NOT EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)))
	BEGIN
		DECLARE @MADH INT=(SELECT MAX(MADH) FROM DONHANG)
		IF(@MADH IS NULL)
			SET @MADH=1
		ELSE
			SET @MADH=@MADH+1

		INSERT INTO DONHANG VALUES(@MADH,@MANV,@MATV,@MACN,GETDATE(),N'Tiếp nhận',@KENHDH,0,0,@PTTT,0)
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_InDH 
	@MANV=2,
	@MATV=1,
	@MACN=1,
	@KENHDH=N'Điện thoại',
	@PTTT=N'Trực tiếp'
GO

EXEC sp_InDH 
	@MANV=2,
	@MATV=1,
	@MACN=1,
	@KENHDH=N'Điện thoại',
	@PTTT=N'Trực tiếp'
GO

EXEC sp_InDH 
	@MANV=2,
	@MATV=1,
	@MACN=1,
	@KENHDH=N'Online',
	@PTTT=N'Trực tiếp'
GO

EXEC sp_InDH 
	@MANV=2,
	@MATV=1,
	@MACN=1,
	@KENHDH=N'Online',
	@PTTT=N'Trực tiếp'
GO
SELECT*FROM DONHANG

--NV UPDATE TÌNH TRẠNG CỦA ĐH
CREATE PROC sp_UpDH @MADH INT,@TRANGTHAI NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	DECLARE @KENHDH NVARCHAR(100)=(SELECT KENHDH FROM DONHANG WHERE MADH=@MADH)
	IF(EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH))
	BEGIN
		IF((@KENHDH='Online')OR(@KENHDH=N'Điện thoại'))
		BEGIN
			IF(@TRANGTHAI IN (N'Tiếp nhận',N'Đang chuẩn bị',N'Đang giao',N'Hoàn tất'))
				UPDATE DONHANG SET TRANGTHAI=@TRANGTHAI WHERE MADH=@MADH
		END
		ELSE
		BEGIN
			IF(@KENHDH=N'Trực tiếp')
			BEGIN
				IF(@TRANGTHAI IN (N'Tiếp nhận',N'Đang chuẩn bị',N'Chờ thanh toán',N'Hoàn tất'))
					UPDATE DONHANG SET TRANGTHAI=@TRANGTHAI WHERE MADH=@MADH
			END
		END	
		
		IF(@TRANGTHAI=N'Hoàn tất')
		BEGIN
			DECLARE @DIEMTL INT,@MATV INT
			SET @MATV=(SELECT MATV FROM DONHANG WHERE MADH=@MADH)
			SET @DIEMTL=(SELECT DIEMTICHLUY FROM THANHVIEN WHERE MATV=@MATV)
			IF(@DIEMTL IS NULL)
				SET @DIEMTL=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
			ELSE
				SET @DIEMTL=(SELECT DIEMTICHLUY FROM THANHVIEN WHERE MATV=@MATV)+(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
			IF(@DIEMTL<=5000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Silver' WHERE MATV=@MATV
			ELSE IF(@DIEMTL>5000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Gold' WHERE MATV=@MATV
			ELSE IF(@DIEMTL>20000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Diamond' WHERE MATV=@MATV
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_UpDH @MADH=1,@TRANGTHAI=N'Hoàn tất'
GO
SELECT*FROM DONHANG
SELECT*FROM THANHVIEN

--KHÁCH HÀNG ONLINE HOẶC NHÂN VIÊN HỦY ĐƠN 
CREATE PROC sp_UpPGH_HuyDon @MADH INT,@HUYDON BIT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH))
	BEGIN
		IF(@HUYDON =1)
		BEGIN
			DECLARE @TRANGTHAI NVARCHAR(100) = (SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)
			IF(@TRANGTHAI=N'Tiếp nhận')
			BEGIN
				UPDATE DONHANG SET TRANGTHAI=N'Đã hủy',HUYDON=@HUYDON WHERE MADH=@MADH
				DECLARE @DEM INT =(SELECT COUNT(*) FROM dbo.CHITIETDONHANG WHERE MADH=@MADH)
				DECLARE @NGAY DATE=(SELECT NGAYDAT FROM DONHANG WHERE MADH=@MADH)
				DECLARE @MACN INT=(SELECT MACN FROM DONHANG WHERE MADH=@MADH)
				DECLARE @TEMP INT=1
				WHILE(@TEMP<=@DEM)
				BEGIN
					DECLARE @MAMON INT=(SELECT TOP 1 MAMON FROM dbo.CHITIETDONHANG WHERE MADH=@MADH ORDER BY NEWID())
					DECLARE @SL INT=(SELECT SL_CONLAI FROM THUCDON WHERE MACN=@MACN AND MAMON=@MAMON AND NGAY=@NGAY)+ (SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
					UPDATE dbo.THUCDON SET SL_CONLAI=@SL WHERE MACN=@MACN AND MAMON=@MAMON AND NGAY=@NGAY
					DELETE dbo.CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON
					SET @TEMP=@TEMP+1
				END
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_UpPGH_HuyDon @MADH=2,@HUYDON=1
GO

--KHÔNG ĐƯỢC XÓA ĐƠN HÀNG, GIỮ LẠI CÁC ĐƠN HÀNG ĐÃ HỦY ĐỂ THỐNG KÊ

/* CHI TIẾT ĐƠN HÀNG */
--INSERT
CREATE PROC sp_InCTDH @MADH INT,@MAMON INT,@SL INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		IF((SELECT SOLUONG FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND T.MAMON=@MAMON AND D.MACN=T.MACN)>=@SL)
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Tiếp nhận')--Trạng thái khác không được tiếp tục thêm món vào đơn
			BEGIN
				DECLARE @THANHTIEN INT,@THANHTIEN_MOI INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_INS FLOAT
				SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
				SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @THANHTIEN_MOI=(SELECT SUM(GIATIEN*@SL) FROM MONAN WHERE MAMON=@MAMON)

				INSERT INTO CHITIETDONHANG VALUES(@MADH,@MAMON,@SL)
				SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI

				IF(@LOAITHE='Silver')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI
				ELSE IF(@LOAITHE='Gold')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.95
				ELSE IF(@LOAITHE='Diamond')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.9

				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_INS WHERE MADH=@MADH
				SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

SELECT*FROM MONAN
SELECT*FROM CHITIETDONHANG
SELECT*FROM DONHANG

EXEC sp_InCTDH 2,3,21
GO

--UPDATE
CREATE PROC sp_UpCTDH @MADH INT,@MAMON INT,@SL INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		IF((SELECT SOLUONG FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND T.MAMON=@MAMON AND D.MACN=T.MACN)>=@SL)
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Tiếp nhận')
			BEGIN
				DECLARE @THANHTIEN INT,@THANHTIEN_MOI INT,@THANHTIEN_CU INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_UP FLOAT,@SL_CU INT
				SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
				SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @THANHTIEN_MOI=(SELECT SUM(GIATIEN*@SL) FROM MONAN WHERE MAMON=@MAMON)
				SET @SL_CU=(SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
				SET @THANHTIEN_CU=(SELECT SUM(GIATIEN*@SL_CU) FROM MONAN WHERE MAMON=@MAMON)

				UPDATE CHITIETDONHANG SET SL=@SL WHERE MADH=@MADH AND MAMON=@MAMON
				SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI - @THANHTIEN_CU 

				IF(@LOAITHE='Silver')
					SET @TONGTIEN_UP=@TONGTIEN+@THANHTIEN_MOI-@THANHTIEN_CU
				ELSE IF(@LOAITHE='Gold')
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.95
				ELSE IF(@LOAITHE='Diamond')
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.9

				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_UP WHERE MADH=@MADH
				SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_UpCTDH @MADH=2,@MAMON=1,@SL=14
GO

--DELETE
CREATE PROC sp_DelCTDH @MADH INT,@MAMON INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH,MAMON FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		DECLARE @THANHTIEN INT,@THANHTIEN_CU INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_DEL FLOAT,@SL_CU INT
		SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
		SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
		SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
		SET @SL_CU=(SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
		SET @THANHTIEN_CU=(SELECT SUM(GIATIEN*@SL_CU) FROM MONAN WHERE MAMON=@MAMON)
				
		DELETE FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON
		SET @THANHTIEN=@THANHTIEN - @THANHTIEN_CU
		
		IF(@LOAITHE='Silver')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU
		ELSE IF(@LOAITHE='Gold')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.95
		ELSE IF(@LOAITHE='Diamond')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.9

		UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_DEL WHERE MADH=@MADH

		IF((SELECT COUNT(*) FROM CHITIETDONHANG WHERE MADH=@MADH)=0)
			UPDATE DONHANG SET TONGTIEN=0,THANHTIEN=0 WHERE MADH=@MADH
		SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO


/*
CREATE PROC sp_CTDH @MADH INT,@MAMON INT,@SL INT,@THAOTAC NVARCHAR(10) --I=Insert, U=Update, D=Delete
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		IF(((SELECT SOLUONG FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND T.MAMON=@MAMON AND D.MACN=T.MACN)>=@SL)OR(@THAOTAC='D'))
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Tiếp nhận')--Trạng thái khác không được tiếp tục thêm/xóa/sửa món trong đơn
			BEGIN
				DECLARE @THANHTIEN INT,@THANHTIEN_MOI INT,@THANHTIEN_CU INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_INS FLOAT,@TONGTIEN_UP FLOAT,@TONGTIEN_DEL FLOAT
				SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
				SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @THANHTIEN_MOI=(SELECT SUM(GIATIEN*@SL) FROM MONAN WHERE MAMON=@MAMON)
				
				IF(@THAOTAC='I')
				BEGIN
					INSERT INTO CHITIETDONHANG VALUES(@MADH,@MAMON,@SL)
					SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI
				END
				ELSE
				BEGIN
					DECLARE @SL_CU INT=(SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
					SET @THANHTIEN_CU=(SELECT SUM(GIATIEN*@SL_CU) FROM MONAN WHERE MAMON=@MAMON)
					IF(@THAOTAC='U')
					BEGIN
						UPDATE CHITIETDONHANG SET SL=@SL WHERE MADH=@MADH AND MAMON=@MAMON
						SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI - @THANHTIEN_CU 
					END
					ELSE IF(@THAOTAC='D')
					BEGIN
						DELETE FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON
						SET @THANHTIEN=@THANHTIEN - @THANHTIEN_CU
					END
				END

				IF(@LOAITHE='Silver')
				BEGIN
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI
					SET @TONGTIEN_UP=@TONGTIEN+@THANHTIEN_MOI-@THANHTIEN_CU
					SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU
				END
				ELSE IF(@LOAITHE='Gold')
				BEGIN
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.95
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.95
					SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.95
				END
				ELSE IF(@LOAITHE='Diamond')
				BEGIN
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.9
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.9
					SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.9
				END

				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_INS WHERE MADH=@MADH AND @THAOTAC='I'
				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_UP WHERE MADH=@MADH AND @THAOTAC='U'
				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_DEL WHERE MADH=@MADH AND @THAOTAC='D'
				IF((SELECT COUNT(*) FROM CHITIETDONHANG WHERE MADH=@MADH)=0)
					UPDATE DONHANG SET TONGTIEN=0,THANHTIEN=0 WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_CTDH 3,1,9,'I'
GO

EXEC sp_CTDH 3,3,4,'U'
GO

EXEC sp_CTDH 3,3,1,'D'
GO

SELECT*FROM CHITIETDONHANG
SELECT*FROM DONHANG
GO
*/

/* PHIẾU GIAO HÀNG */
--INSERT
CREATE PROC sp_InPGH 
	@MADH INT,
	@NVGIAOHANG INT,
	@TENKH NVARCHAR(100),
	@SDT VARCHAR(100),
	@DIACHI NVARCHAR(100),
	@PHUONG NVARCHAR(100),
	@QUAN_HUYEN NVARCHAR(100),
	@TINH_TP NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH AND TRANGTHAI=N'Tiếp nhận'))
	BEGIN
		IF(EXISTS(SELECT N.MANV FROM NHANVIEN N,DONHANG D WHERE N.MANV=@NVGIAOHANG AND D.MACN=N.MACN AND D.MADH=@MADH AND N.CHUCVU=N'Giao hàng'))
		BEGIN
			IF(@MADH NOT IN (SELECT MADH FROM PHIEUGIAOHANG))--1 đơn hàng chỉ giao 1 lần
			BEGIN
				DECLARE @SO_PGIAO INT,@CHIPHI INT,@TGGIAO TIME,@P NVARCHAR(100),@Q NVARCHAR(100),@TP NVARCHAR(100)
				SET @SO_PGIAO =(SELECT MAX(SO_PGIAO) FROM PHIEUGIAOHANG)
				SET @P=(SELECT PHUONG FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)
				SET @Q=(SELECT QUAN_HUYEN FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)
				SET @TP=(SELECT TINH_TP FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)

				IF(@SO_PGIAO IS NULL)
					SET @SO_PGIAO=1
				ELSE 
					SET @SO_PGIAO=@SO_PGIAO+1

				IF(@TINH_TP=@TP)
				BEGIN
					IF(@QUAN_HUYEN=@Q)
					BEGIN
						IF(@PHUONG=@P)
							SET @CHIPHI=0
						ELSE
							SET @CHIPHI=20000
					END
					ELSE
						SET @CHIPHI=50000
					SET @TGGIAO=DATEADD(HOUR,3,GETDATE())
					INSERT INTO PHIEUGIAOHANG VALUES(@SO_PGIAO,@MADH,@NVGIAOHANG,@TENKH,@SDT,@DIACHI,@PHUONG,@QUAN_HUYEN,@TINH_TP,@CHIPHI,@TGGIAO)
					DECLARE @TONGTIEN FLOAT =(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)+@CHIPHI
					UPDATE DONHANG SET TRANGTHAI=N'Đang giao',TONGTIEN=@TONGTIEN WHERE MADH=@MADH
				END
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_InPGH @MADH=3,
	@NVGIAOHANG=1,
	@TENKH=N'A',
	@SDT='0222222123',
	@DIACHI='1',
	@PHUONG='1',
	@QUAN_HUYEN=N'Huyện Nhà Bè',
	@TINH_TP=N'TP HCM'
GO
SELECT*FROM PHIEUGIAOHANG
SELECT*FROM NHANVIEN
SELECT*FROM CHINHANH
SELECT*FROM DONHANG

CREATE PROC sp_UpPGIAO @SO_PGIAO INT,@MANV INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT SO_PGIAO FROM PHIEUGIAOHANG WHERE SO_PGIAO=@SO_PGIAO))
	BEGIN
		IF(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Giao hàng'))
		BEGIN
			DECLARE @MADH INT=(SELECT MADH FROM PHIEUGIAOHANG WHERE SO_PGIAO=@SO_PGIAO)
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Đang giao')
				UPDATE PHIEUGIAOHANG SET NVGIAOHANG=@MANV WHERE SO_PGIAO=@SO_PGIAO
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

EXEC sp_UpPGIAO 3,1
GO

--KHÔNG CHO PHÉP DELETE PGH

--NHÂN VIÊN SỬA TV CÙNG CN
CREATE PROC sp_UpTTTV @MANV INT,@MATV INT,
	@TENTV NVARCHAR(100),
	@CMND VARCHAR(20),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(100),
	@EMAIL NVARCHAR(100)
AS
	IF(EXISTS(SELECT MANV FROM NHANVIEN N,THANHVIEN T WHERE MANV=@MANV AND CHUCVU=N'Quản lí khách hàng' AND N.MACN=T.CHINHANHDK AND T.MATV=@MATV))
	BEGIN
		UPDATE THANHVIEN SET TENTV=@TENTV,CMND=@CMND,NGAYSINH=@NGAYSINH,DIACHI=@DIACHI,EMAIL=@EMAIL WHERE MATV=@MATV
	END
GO
EXEC sp_UpTTTV @MANV=3,@MATV=1,
	@TENTV=N'Dương (K CÓ NGUYỄN) Khánh Vi',
	@CMND='365213809',
	@NGAYSINH='1999-04-24',
	@DIACHI=N'Tiệm cầm đồ Anh Vũ, Huyện An Phú, Tỉnh An Giang',
	@EMAIL='quinnduong99@gmail.com'
GO
INSERT INTO NHANVIEN VALUES (3,1,N'A','A',N'Quản lí khách hàng')

