USE HuongViet
GO

/* ĐƠN HÀNG */
-- NV INSERT ĐƠN HÀNG
CREATE PROC sp_InDH 
	@MANV INT,
	@MATV INT,
	@MACN INT,
	@KENHDH NVARCHAR(100),
	@PTTT NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF((EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND MACN=@MACN))AND(EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)))
	BEGIN
		DECLARE @MADH INT=(SELECT MAX(MADH) FROM DONHANG)
		IF(@MADH IS NULL)
			SET @MADH=1
		ELSE
			SET @MADH=@MADH+1

		INSERT INTO DONHANG VALUES(@MADH,@MANV,@MATV,@MACN,GETDATE(),N'Tiếp nhận',@KENHDH,0,0,@PTTT,0)
		SELECT*FROM DONHANG WHERE MADH=@MADH
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--NV UPDATE TÌNH TRẠNG CỦA ĐH
CREATE PROC sp_UpDH @MADH INT,@TRANGTHAI NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	DECLARE @KENHDH NVARCHAR(100)=(SELECT KENHDH FROM DONHANG WHERE MADH=@MADH)
	IF(EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH))
	BEGIN
		IF((@KENHDH='Online')OR(@KENHDH=N'Điện thoại'))
		BEGIN
			IF(@TRANGTHAI IN (N'Tiếp nhận',N'Đang chuẩn bị',N'Đang giao',N'Hoàn tất'))
				UPDATE DONHANG SET TRANGTHAI=@TRANGTHAI WHERE MADH=@MADH
		END
		ELSE
		BEGIN
			IF(@KENHDH=N'Trực tiếp')
			BEGIN
				IF(@TRANGTHAI IN (N'Tiếp nhận',N'Đang chuẩn bị',N'Chờ thanh toán',N'Hoàn tất'))
					UPDATE DONHANG SET TRANGTHAI=@TRANGTHAI WHERE MADH=@MADH
			END
		END	
		
		IF(@TRANGTHAI=N'Hoàn tất')
		BEGIN
			DECLARE @DIEMTL INT,@MATV INT
			SET @MATV=(SELECT MATV FROM DONHANG WHERE MADH=@MADH)
			SET @DIEMTL=(SELECT DIEMTICHLUY FROM THANHVIEN WHERE MATV=@MATV)
			IF(@DIEMTL IS NULL)
				SET @DIEMTL=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
			ELSE
				SET @DIEMTL=@DIEMTL+(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)

			IF(@DIEMTL<=5000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Silver' WHERE MATV=@MATV
			ELSE IF(@DIEMTL>5000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Gold' WHERE MATV=@MATV
			ELSE IF(@DIEMTL>20000000)
				UPDATE THANHVIEN SET DIEMTICHLUY=@DIEMTL,LOAITHE='Diamond' WHERE MATV=@MATV
		END
		SELECT*FROM DONHANG WHERE MADH=@MADH
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--KHÁCH HOẶC NHÂN VIÊN HỦY ĐƠN 
CREATE PROC sp_UpDH_HuyDon @MADH INT,@HUYDON BIT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH))
	BEGIN
		IF(@HUYDON =1)
		BEGIN
			DECLARE @TRANGTHAI NVARCHAR(100) = (SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)
			IF(@TRANGTHAI=N'Tiếp nhận')
			BEGIN
				UPDATE DONHANG SET TRANGTHAI=N'Đã hủy',HUYDON=@HUYDON WHERE MADH=@MADH
				DECLARE @DEM INT =(SELECT COUNT(*) FROM dbo.CHITIETDONHANG WHERE MADH=@MADH)
				DECLARE @NGAY DATE=(SELECT NGAYDAT FROM DONHANG WHERE MADH=@MADH)
				DECLARE @MACN INT=(SELECT MACN FROM DONHANG WHERE MADH=@MADH)
				DECLARE @TEMP INT=1
				WHILE(@TEMP<=@DEM)
				BEGIN
					DECLARE @MAMON INT=(SELECT TOP 1 MAMON FROM dbo.CHITIETDONHANG WHERE MADH=@MADH ORDER BY NEWID())
					DECLARE @SL INT=(SELECT SL_CONLAI FROM THUCDON WHERE MACN=@MACN AND MAMON=@MAMON AND NGAY=@NGAY)+ (SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
					UPDATE dbo.THUCDON SET SL_CONLAI=@SL WHERE MACN=@MACN AND MAMON=@MAMON AND NGAY=@NGAY
					DELETE dbo.CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON
					SET @TEMP=@TEMP+1
				END
			END
			SELECT*FROM DONHANG WHERE MADH=@MADH
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--KH VÃNG LAI XEM ĐƠN HÀNG 
CREATE PROC sp_ViewVL_DH @TENKH NVARCHAR(100),@SDT VARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DHTRUCTUYEN WHERE TENKH=@TENKH AND SDT=@SDT))
	BEGIN
		SELECT D.MADH, MANV, MACN, NGAYDAT, TRANGTHAI, KENHDH, THANHTIEN, TONGTIEN, PTTT, HUYDON, NVGIAOHANG, TENKH, SDT, SONHA, PHUONG, QUAN_HUYEN, TINH_TP, CHIPHI, TGGIAO
		FROM DONHANG D, DHTRUCTUYEN DT WHERE DT.MADH=D.MADH AND TENKH=@TENKH AND SDT=@SDT
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--THÀNH VIÊN XEM ĐƠN HÀNG 
CREATE PROC sp_ViewTV_DH @MATV INT,@MATKHAU VARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THANHVIEN T WHERE T.MATV=D.MATV AND T.MATV=@MATV AND T.MATKHAU=@MATKHAU))
	BEGIN
		SELECT D.MADH, MANV, D.MATV, MACN, NGAYDAT, TRANGTHAI, KENHDH, THANHTIEN, TONGTIEN, PTTT, HUYDON, NVGIAOHANG, TENKH, SDT, SONHA, PHUONG, QUAN_HUYEN, TINH_TP, CHIPHI, TGGIAO
		FROM DONHANG D, THANHVIEN T, DHTRUCTUYEN DT WHERE D.MADH=DT.MADH AND T.MATV=D.MATV AND T.MATV=@MATV AND T.MATKHAU=@MATKHAU
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--Khi khách hàng xem các đơn hàng xong sẽ ghi nhớ mã đơn hàng để hủy đơn trong store sp_UpDH_HuyDon

/* CHI TIẾT ĐƠN HÀNG */
--INSERT
CREATE PROC sp_InCTDH @MADH INT,@MAMON INT,@SL INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		IF((SELECT SOLUONG FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND T.MAMON=@MAMON AND D.MACN=T.MACN)>=@SL)
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Tiếp nhận')--Trạng thái khác không được tiếp tục thêm món vào đơn
			BEGIN
				DECLARE @THANHTIEN INT,@THANHTIEN_MOI INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_INS FLOAT
				SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
				SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @THANHTIEN_MOI=(SELECT SUM(GIATIEN*@SL) FROM MONAN WHERE MAMON=@MAMON)

				INSERT INTO CHITIETDONHANG VALUES(@MADH,@MAMON,@SL)
				SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI

				IF(@LOAITHE='Silver')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI
				ELSE IF(@LOAITHE='Gold')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.95
				ELSE IF(@LOAITHE='Diamond')
					SET @TONGTIEN_INS=@TONGTIEN+@THANHTIEN_MOI*0.9

				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_INS WHERE MADH=@MADH
				SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--UPDATE
CREATE PROC sp_UpCTDH @MADH INT,@MAMON INT,@SL INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		IF((SELECT SOLUONG FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND T.MAMON=@MAMON AND D.MACN=T.MACN)>=@SL)
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Tiếp nhận')
			BEGIN
				DECLARE @THANHTIEN INT,@THANHTIEN_MOI INT,@THANHTIEN_CU INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_UP FLOAT,@SL_CU INT
				SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
				SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
				SET @THANHTIEN_MOI=(SELECT SUM(GIATIEN*@SL) FROM MONAN WHERE MAMON=@MAMON)
				SET @SL_CU=(SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
				SET @THANHTIEN_CU=(SELECT SUM(GIATIEN*@SL_CU) FROM MONAN WHERE MAMON=@MAMON)

				UPDATE CHITIETDONHANG SET SL=@SL WHERE MADH=@MADH AND MAMON=@MAMON
				SET @THANHTIEN=@THANHTIEN + @THANHTIEN_MOI - @THANHTIEN_CU 

				IF(@LOAITHE='Silver')
					SET @TONGTIEN_UP=@TONGTIEN+@THANHTIEN_MOI-@THANHTIEN_CU
				ELSE IF(@LOAITHE='Gold')
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.95
				ELSE IF(@LOAITHE='Diamond')
					SET @TONGTIEN_UP=@TONGTIEN+(@THANHTIEN_MOI-@THANHTIEN_CU)*0.9

				UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_UP WHERE MADH=@MADH
				SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--DELETE
CREATE PROC sp_DelCTDH @MADH INT,@MAMON INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH,MAMON FROM DONHANG D, THUCDON T WHERE MADH=@MADH AND D.MACN=T.MACN))
	BEGIN
		DECLARE @THANHTIEN INT,@THANHTIEN_CU INT,@TONGTIEN FLOAT,@LOAITHE NVARCHAR(100),@TONGTIEN_DEL FLOAT,@SL_CU INT
		SET @TONGTIEN=(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)
		SET @LOAITHE=(SELECT LOAITHE FROM DONHANG D,THANHVIEN T WHERE D.MADH=@MADH AND D.MATV=T.MATV)
		SET @THANHTIEN=(SELECT THANHTIEN FROM DONHANG WHERE MADH=@MADH)
		SET @SL_CU=(SELECT SL FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON)
		SET @THANHTIEN_CU=(SELECT SUM(GIATIEN*@SL_CU) FROM MONAN WHERE MAMON=@MAMON)
				
		DELETE FROM CHITIETDONHANG WHERE MADH=@MADH AND MAMON=@MAMON
		SET @THANHTIEN=@THANHTIEN - @THANHTIEN_CU
		
		IF(@LOAITHE='Silver')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU
		ELSE IF(@LOAITHE='Gold')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.95
		ELSE IF(@LOAITHE='Diamond')
			SET @TONGTIEN_DEL=@TONGTIEN-@THANHTIEN_CU*0.9

		UPDATE DONHANG SET THANHTIEN=@THANHTIEN,TONGTIEN=@TONGTIEN_DEL WHERE MADH=@MADH

		IF((SELECT COUNT(*) FROM CHITIETDONHANG WHERE MADH=@MADH)=0)
			UPDATE DONHANG SET TONGTIEN=0,THANHTIEN=0 WHERE MADH=@MADH
		SELECT*FROM CHITIETDONHANG WHERE MADH=@MADH
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

/* ĐƠN HÀNG TRỰC TUYẾN */
--INSERT
CREATE PROC sp_InDHTT 
	@MADH INT,
	@NVGIAOHANG INT,
	@TENKH NVARCHAR(100),
	@SDT VARCHAR(100),
	@SONHA NVARCHAR(100),
	@PHUONG NVARCHAR(100),
	@QUAN_HUYEN NVARCHAR(100),
	@TINH_TP NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF((EXISTS(SELECT MADH FROM DONHANG WHERE MADH=@MADH AND TRANGTHAI=N'Tiếp nhận'))AND((SELECT KENHDH FROM DONHANG WHERE MADH=@MADH)!=N'Trực tiếp'))
	BEGIN
		IF(EXISTS(SELECT N.MANV FROM NHANVIEN N,DONHANG D WHERE N.MANV=@NVGIAOHANG AND D.MACN=N.MACN AND D.MADH=@MADH AND N.CHUCVU=N'Giao hàng'))
		BEGIN
			IF(@MADH NOT IN (SELECT MADH FROM DHTRUCTUYEN))--1 đơn hàng chỉ giao 1 lần
			BEGIN
				DECLARE @CHIPHI INT,@TGGIAO TIME,@P NVARCHAR(100),@Q NVARCHAR(100),@TP NVARCHAR(100)
				SET @P=(SELECT PHUONG FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)
				SET @Q=(SELECT QUAN_HUYEN FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)
				SET @TP=(SELECT TINH_TP FROM CHINHANH C,DONHANG D WHERE D.MACN=C.MACN AND D.MADH=@MADH)
				
				IF(@TINH_TP=@TP)
				BEGIN
					IF(@QUAN_HUYEN=@Q)
					BEGIN
						IF(@PHUONG=@P)
							SET @CHIPHI=0
						ELSE
							SET @CHIPHI=20000
					END
					ELSE
						SET @CHIPHI=50000
					SET @TGGIAO=DATEADD(HOUR,3,GETDATE())
					INSERT INTO DHTRUCTUYEN VALUES(@MADH,@NVGIAOHANG,@TENKH,@SDT,@SONHA,@PHUONG,@QUAN_HUYEN,@TINH_TP,@CHIPHI,@TGGIAO)
					DECLARE @TONGTIEN FLOAT =(SELECT TONGTIEN FROM DONHANG WHERE MADH=@MADH)+@CHIPHI
					UPDATE DONHANG SET TRANGTHAI=N'Đang giao',TONGTIEN=@TONGTIEN WHERE MADH=@MADH
				END
				SELECT*FROM DHTRUCTUYEN WHERE MADH=@MADH
			END
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--UPDATE
CREATE PROC sp_UpDHTT @MADH INT,@MANV INT
AS
BEGIN TRAN
BEGIN TRY
	IF(EXISTS(SELECT MADH FROM DHTRUCTUYEN WHERE MADH=@MADH))
	BEGIN
		IF(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Giao hàng'))
		BEGIN
			IF((SELECT TRANGTHAI FROM DONHANG WHERE MADH=@MADH)=N'Đang giao')
				UPDATE DHTRUCTUYEN SET NVGIAOHANG=@MANV WHERE MADH=@MADH
		END
	END
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
GO

--KHÔNG CHO PHÉP DELETE DHTT