USE HuongViet
GO

/*Người thực hiện: Nguyễn Thị Ngọc Hân, MSSV: 1712415, Mã nhóm: 8*/

--LỖI DIRTY READ
BEGIN TRAN
UPDATE THUCDON
SET SL_CONLAI= 4 WHERE MACN = 1 AND MAMON=1 AND NGAY='2019-30-11'
waitfor delay'00:00:05'
ROLLBACK

---LỖI UNREPEATABLE READ
BEGIN TRAN
SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
waitfor delay'00:00:15'

SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1 AND NGAY='2019-11-30'
COMMIT

--LỖI PHANTOM
BEGIN TRAN
SELECT * FROM THANHVIEN WHERE CHINHANHDK=1
waitfor delay'00:00:15'

SELECT * FROM THANHVIEN WHERE CHINHANHDK=1
COMMIT

--LỖI LOST UPDATE
BEGIN TRAN
SELECT SL FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1
waitfor delay'00:00:05'

UPDATE CHITIETDONHANG SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1
COMMIT

--LỖI DEADLOCK
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT SL FROM CHITIETDONHANG
WHERE MADH=1 AND MAMON=1
waitfor delay'00:00:05'

UPDATE CHITIETDONHANG SET SL=( SELECT SL FROM CHITIETDONHANG WHERE MADH=1 AND MAMON=1)+1
WHERE MADH=1 AND MAMON=1
COMMIT

/*Người thực hiện: Lai Gia Phú, MSSV: 1712662, Mã nhóm: 8*/

--Dirty Read
BEGIN TRAN
EXEC sp_CapNhatSoPhanAn 1,1,'2019-01-01',50,10
Waitfor delay '00:00:10'
ROLLBACK TRAN

--Unrepeatable Read
BEGIN TRAN
EXEC sp_XemThucDon 1,'2020-01-01'
Waitfor delay '00:00:10'
EXEC sp_XemThucDon 1,'2020-01-01'
COMMIT TRAN

--Phantom
BEGIN TRAN
EXEC sp_XemThucDon 1,'2020-01-01'
Waitfor delay '00:00:10'
EXEC sp_XemThucDon 1,'2020-01-01'
COMMIT TRAN

--Lost Update
BEGIN TRAN
EXEC sp_XemThucDon 1,'2020-01-01'
Waitfor delay '00:00:10'
EXEC sp_CapNhatSoPhanAn 1,1,'2020-01-01',50,45
COMMIT TRAN

--Deadlock
BEGIN TRAN
EXEC sp_CapNhatSoPhanAn 1,1,'2019-01-01',50,40
Waitfor delay '00:00:05'
EXEC sp_XemThucDon 2,'2019-01-01'
COMMIT TRAN

/*Người thực hiện: Nguyễn Đoàn Tấn Phúc, MSSV: 1712671, Mã nhóm: 8*/

--Dirty Read
BEGIN TRAN
EXEC sp_ThemMonThucDon 1,2,'2020-01-01',50,50
Waitfor delay '00:00:10'
ROLLBACK TRAN

-- Unrepeatable Read
BEGIN TRAN
EXEC sp_XemThucDon 1,'2020-01-01'
Waitfor delay '00:00:10'
EXEC sp_XemThucDon 1,'2020-01-01'
COMMIT TRAN

--Phantom
BEGIN TRAN
EXEC sp_ThongKeTheoNgayCN 1
Waitfor delay '00:00:10'
EXEC sp_ThongKeTheoNgayCN 1
COMMIT TRAN

--Lost update
BEGIN TRAN
select * from THANHVIEN where MATV = 1
Waitfor delay '00:00:10'
EXEC sp_UPTHETV3 1,1,2
COMMIT TRAN

--Deadlock
BEGIN TRAN
EXEC sp_ThemMonThucDon 1,1,'2019-01-02',50,50
Waitfor delay '00:00:05'
EXEC sp_XemThucDon 2,'2019-01-02'
COMMIT TRAN

/*Người thực hiện: Trịnh Đức Thanh, MSSV: 1712769, Mã nhóm: 8*/

--Lỗi 1: Dirty Read
BEGIN TRAN
UPDATE MONAN 
SET GIATIEN=25000 
WHERE MAMON=2
Waitfor delay '00:00:20'
ROLLBACK

--Lỗi 2: Unrepeatable
BEGIN TRAN
SELECT SL_CONLAI 
FROM THUCDON 
WHERE MAMON = 1 AND MACN = 1
waitfor delay'00:00:20'

SELECT SL_CONLAI
FROM THUCDON 
WHERE MAMON = 1 AND MACN = 1
COMMIT

--Lỗi 3: Phantom
BEGIN TRAN
SELECT * FROM THANHVIEN 
WHERE LOAITHE='Gold' AND CHINHANHDK=1
waitfor delay'00:00:20'

SELECT * FROM THANHVIEN 
WHERE LOAITHE='Gold' AND CHINHANHDK=1
COMMIT

--Lỗi 4: Lost Update
BEGIN TRAN
SELECT SL_CONLAI 
FROM THUCDON 
WHERE MAMON = 1 AND MACN = 1
waitfor delay'00:00:20'

UPDATE THUCDON 
SET SL_CONLAI =19 
WHERE MAMON = 1 AND MACN = 1
COMMIT

--Lỗi 5: Deadlock
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT*FROM DONHANG 
WHERE MADH=3
waitfor delay '00:00:20'

UPDATE DONHANG 
SET TRANGTHAI=N'Đang chuẩn bị' 
WHERE MADH=3
COMMIT


/*Người thực hiện: Dương Khánh Vi, MSSV: 1712899, Mã nhóm: 8*/

-- Lỗi 1: Dirty Read
BEGIN TRAN
UPDATE THUCDON
SET SL_CONLAI = 0
WHERE MACN = 1 AND MAMON = 1
waitfor delay '00:00:10'
ROLLBACK
GO

-- Lỗi 2: Unrepeatable Read
BEGIN TRAN
SELECT * FROM THANHVIEN WHERE MATV = 1 
waitfor delay '00:00:15'
SELECT * FROM THANHVIEN WHERE MATV = 1 
COMMIT
GO

-- Lỗi 3: Phantom
BEGIN TRAN
SELECT * FROM THANHVIEN WHERE CHINHANHDK = 2
waitfor delay '00:00:10'
SELECT * FROM THANHVIEN WHERE CHINHANHDK = 2
COMMIT
GO

-- Lỗi 4: Lost update
BEGIN TRAN
SELECT DIACHI FROM THANHVIEN WHERE MATV = 1
waitfor delay '00:00:10'
UPDATE THANHVIEN
SET DIACHI = N'Khu đô thị Sala, phường 3, quận 2, TPHCM' WHERE MATV = 1
COMMIT
GO

-- Lỗi 5: Deadlock
BEGIN TRAN
set tran isolation level SERIALIZABLE
SELECT DIACHI FROM THANHVIEN WHERE MATV = 1
waitfor delay '00:00:10'
UPDATE THANHVIEN
SET DIACHI = N'Khu đô thị Sala, phường 3, quận 2, TPHCM' WHERE MATV = 1
COMMIT