--Người thực hiện: Trịnh Đức Thanh - 1712769

--Lỗi 1: Dirty Read
BEGIN TRAN
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
SELECT * FROM MONAN
COMMIT

SELECT*FROM MONAN

--Người thực hiện: Trịnh Đức Thanh - 1712769

--Lỗi 2: Unrepeatable
BEGIN TRAN
UPDATE THUCDON 
SET SL_CONLAI = 30 
WHERE MAMON = 1 AND MACN = 1
COMMIT

--Người thực hiện: Trịnh Đức Thanh - 1712769

--Lỗi 3: Phantom
BEGIN TRAN
UPDATE THANHVIEN 
SET LOAITHE='Gold' 
WHERE MATV=23 
COMMIT

--Người thực hiện: Trịnh Đức Thanh - 1712769

--Lỗi 4: Lost Update
BEGIN TRAN
SELECT SL_CONLAI
FROM THUCDON 
WHERE MAMON = 1 AND MACN = 1

UPDATE THUCDON 
SET SL_CONLAI =17 
WHERE MAMON = 1 AND MACN = 1
COMMIT

SELECT SL_CONLAI FROM THUCDON WHERE MAMON = 1 AND MACN = 1


--Người thực hiện: Trịnh Đức Thanh - 1712769

--Lỗi 5: Deadlock
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
SELECT*FROM DONHANG 
WHERE MADH=3

UPDATE DONHANG 
SET HUYDON=1, TRANGTHAI=N'Đã hủy' 
WHERE MADH=3
COMMIT

